# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Copyright Year Updater"
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
        with:
          ref: master

      - name: Ensure year in copyright is up to date
        shell: bash
        run: |
          python tools/update_copyright.py . $(date +%Y)

      - name: Check for file changes
        id: git-status
        run: |
          echo $(git status --porcelain)
          echo "changes=$(git status --porcelain | tr -d '\n')" >> $GITHUB_OUTPUT

      - uses: webfactory/ssh-agent@v0.9.0
        if: steps.git-status.outputs.changes != ''
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure Git
        if: steps.git-status.outputs.changes != ''
        run: |
          git config user.name "genai-factory-robot"
          git config user.email "genai-factory-robot@google.com"

      - name: Commit and push feature branch
        if: steps.git-status.outputs.changes != ''
        run: |
          git remote set-url origin git@github.com:GoogleCloudPlatform/genai-factory.git
          git checkout -b fabric-upgrade-${{ needs.prerequisites.outputs.latest_tag }}
          git add .
          git commit -m "[GH Actions] Update Fabric to ${{ needs.prerequisites.outputs.latest_tag }}"
          git push --set-upstream origin fabric-upgrade-${{ needs.prerequisites.outputs.latest_tag }}

      - name: Create PR
        if: steps.git-status.outputs.changes != ''
        run: |
          gh pr create \
            --title "[Copyright year automated check] - Update to $(date +%Y)" \
            --head fabric-upgrade-${{ needs.prerequisites.outputs.latest_tag }} \
            --base master \
            --body "Makes sure copyright year for all files is set to $(date +%Y)"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
